// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "author", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeInt},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_posts_comments",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "author", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
	}
	// PostLikesColumns holds the columns for the "post_likes" table.
	PostLikesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeInt},
	}
	// PostLikesTable holds the schema information for the "post_likes" table.
	PostLikesTable = &schema.Table{
		Name:       "post_likes",
		Columns:    PostLikesColumns,
		PrimaryKey: []*schema.Column{PostLikesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_likes_posts_likes",
				Columns:    []*schema.Column{PostLikesColumns[3]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "postlike_post_id_user",
				Unique:  true,
				Columns: []*schema.Column{PostLikesColumns[3], PostLikesColumns[1]},
			},
		},
	}
	// PostViewsColumns holds the columns for the "post_views" table.
	PostViewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeInt},
	}
	// PostViewsTable holds the schema information for the "post_views" table.
	PostViewsTable = &schema.Table{
		Name:       "post_views",
		Columns:    PostViewsColumns,
		PrimaryKey: []*schema.Column{PostViewsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_views_posts_views",
				Columns:    []*schema.Column{PostViewsColumns[3]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
		PostsTable,
		PostLikesTable,
		PostViewsTable,
	}
)

func init() {
	CommentsTable.ForeignKeys[0].RefTable = PostsTable
	PostLikesTable.ForeignKeys[0].RefTable = PostsTable
	PostViewsTable.ForeignKeys[0].RefTable = PostsTable
}
