// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kafka_laba/data-service/data/ent/post"
	"kafka_laba/data-service/data/ent/postlike"
	"kafka_laba/data-service/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostLikeUpdate is the builder for updating PostLike entities.
type PostLikeUpdate struct {
	config
	hooks    []Hook
	mutation *PostLikeMutation
}

// Where appends a list predicates to the PostLikeUpdate builder.
func (plu *PostLikeUpdate) Where(ps ...predicate.PostLike) *PostLikeUpdate {
	plu.mutation.Where(ps...)
	return plu
}

// SetPostID sets the "post_id" field.
func (plu *PostLikeUpdate) SetPostID(i int) *PostLikeUpdate {
	plu.mutation.SetPostID(i)
	return plu
}

// SetUser sets the "user" field.
func (plu *PostLikeUpdate) SetUser(s string) *PostLikeUpdate {
	plu.mutation.SetUser(s)
	return plu
}

// SetCreatedAt sets the "created_at" field.
func (plu *PostLikeUpdate) SetCreatedAt(t time.Time) *PostLikeUpdate {
	plu.mutation.SetCreatedAt(t)
	return plu
}

// SetPost sets the "post" edge to the Post entity.
func (plu *PostLikeUpdate) SetPost(p *Post) *PostLikeUpdate {
	return plu.SetPostID(p.ID)
}

// Mutation returns the PostLikeMutation object of the builder.
func (plu *PostLikeUpdate) Mutation() *PostLikeMutation {
	return plu.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (plu *PostLikeUpdate) ClearPost() *PostLikeUpdate {
	plu.mutation.ClearPost()
	return plu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (plu *PostLikeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(plu.hooks) == 0 {
		if err = plu.check(); err != nil {
			return 0, err
		}
		affected, err = plu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostLikeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = plu.check(); err != nil {
				return 0, err
			}
			plu.mutation = mutation
			affected, err = plu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(plu.hooks) - 1; i >= 0; i-- {
			if plu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = plu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, plu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (plu *PostLikeUpdate) SaveX(ctx context.Context) int {
	affected, err := plu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (plu *PostLikeUpdate) Exec(ctx context.Context) error {
	_, err := plu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plu *PostLikeUpdate) ExecX(ctx context.Context) {
	if err := plu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (plu *PostLikeUpdate) check() error {
	if v, ok := plu.mutation.User(); ok {
		if err := postlike.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "PostLike.user": %w`, err)}
		}
	}
	if _, ok := plu.mutation.PostID(); plu.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostLike.post"`)
	}
	return nil
}

func (plu *PostLikeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postlike.Table,
			Columns: postlike.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postlike.FieldID,
			},
		},
	}
	if ps := plu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := plu.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postlike.FieldUser,
		})
	}
	if value, ok := plu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postlike.FieldCreatedAt,
		})
	}
	if plu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postlike.PostTable,
			Columns: []string{postlike.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := plu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postlike.PostTable,
			Columns: []string{postlike.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, plu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postlike.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PostLikeUpdateOne is the builder for updating a single PostLike entity.
type PostLikeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostLikeMutation
}

// SetPostID sets the "post_id" field.
func (pluo *PostLikeUpdateOne) SetPostID(i int) *PostLikeUpdateOne {
	pluo.mutation.SetPostID(i)
	return pluo
}

// SetUser sets the "user" field.
func (pluo *PostLikeUpdateOne) SetUser(s string) *PostLikeUpdateOne {
	pluo.mutation.SetUser(s)
	return pluo
}

// SetCreatedAt sets the "created_at" field.
func (pluo *PostLikeUpdateOne) SetCreatedAt(t time.Time) *PostLikeUpdateOne {
	pluo.mutation.SetCreatedAt(t)
	return pluo
}

// SetPost sets the "post" edge to the Post entity.
func (pluo *PostLikeUpdateOne) SetPost(p *Post) *PostLikeUpdateOne {
	return pluo.SetPostID(p.ID)
}

// Mutation returns the PostLikeMutation object of the builder.
func (pluo *PostLikeUpdateOne) Mutation() *PostLikeMutation {
	return pluo.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (pluo *PostLikeUpdateOne) ClearPost() *PostLikeUpdateOne {
	pluo.mutation.ClearPost()
	return pluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pluo *PostLikeUpdateOne) Select(field string, fields ...string) *PostLikeUpdateOne {
	pluo.fields = append([]string{field}, fields...)
	return pluo
}

// Save executes the query and returns the updated PostLike entity.
func (pluo *PostLikeUpdateOne) Save(ctx context.Context) (*PostLike, error) {
	var (
		err  error
		node *PostLike
	)
	if len(pluo.hooks) == 0 {
		if err = pluo.check(); err != nil {
			return nil, err
		}
		node, err = pluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostLikeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pluo.check(); err != nil {
				return nil, err
			}
			pluo.mutation = mutation
			node, err = pluo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pluo.hooks) - 1; i >= 0; i-- {
			if pluo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pluo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pluo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PostLike)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PostLikeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pluo *PostLikeUpdateOne) SaveX(ctx context.Context) *PostLike {
	node, err := pluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pluo *PostLikeUpdateOne) Exec(ctx context.Context) error {
	_, err := pluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pluo *PostLikeUpdateOne) ExecX(ctx context.Context) {
	if err := pluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pluo *PostLikeUpdateOne) check() error {
	if v, ok := pluo.mutation.User(); ok {
		if err := postlike.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "PostLike.user": %w`, err)}
		}
	}
	if _, ok := pluo.mutation.PostID(); pluo.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostLike.post"`)
	}
	return nil
}

func (pluo *PostLikeUpdateOne) sqlSave(ctx context.Context) (_node *PostLike, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postlike.Table,
			Columns: postlike.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postlike.FieldID,
			},
		},
	}
	id, ok := pluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostLike.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postlike.FieldID)
		for _, f := range fields {
			if !postlike.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postlike.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pluo.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postlike.FieldUser,
		})
	}
	if value, ok := pluo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postlike.FieldCreatedAt,
		})
	}
	if pluo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postlike.PostTable,
			Columns: []string{postlike.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pluo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postlike.PostTable,
			Columns: []string{postlike.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostLike{config: pluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postlike.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
