// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kafka_laba/data-service/data/ent/post"
	"kafka_laba/data-service/data/ent/postview"
	"kafka_laba/data-service/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostViewQuery is the builder for querying PostView entities.
type PostViewQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PostView
	withPost   *PostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostViewQuery builder.
func (pvq *PostViewQuery) Where(ps ...predicate.PostView) *PostViewQuery {
	pvq.predicates = append(pvq.predicates, ps...)
	return pvq
}

// Limit adds a limit step to the query.
func (pvq *PostViewQuery) Limit(limit int) *PostViewQuery {
	pvq.limit = &limit
	return pvq
}

// Offset adds an offset step to the query.
func (pvq *PostViewQuery) Offset(offset int) *PostViewQuery {
	pvq.offset = &offset
	return pvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pvq *PostViewQuery) Unique(unique bool) *PostViewQuery {
	pvq.unique = &unique
	return pvq
}

// Order adds an order step to the query.
func (pvq *PostViewQuery) Order(o ...OrderFunc) *PostViewQuery {
	pvq.order = append(pvq.order, o...)
	return pvq
}

// QueryPost chains the current query on the "post" edge.
func (pvq *PostViewQuery) QueryPost() *PostQuery {
	query := &PostQuery{config: pvq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postview.Table, postview.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, postview.PostTable, postview.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(pvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostView entity from the query.
// Returns a *NotFoundError when no PostView was found.
func (pvq *PostViewQuery) First(ctx context.Context) (*PostView, error) {
	nodes, err := pvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postview.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pvq *PostViewQuery) FirstX(ctx context.Context) *PostView {
	node, err := pvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostView ID from the query.
// Returns a *NotFoundError when no PostView ID was found.
func (pvq *PostViewQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postview.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pvq *PostViewQuery) FirstIDX(ctx context.Context) int {
	id, err := pvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostView entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostView entity is found.
// Returns a *NotFoundError when no PostView entities are found.
func (pvq *PostViewQuery) Only(ctx context.Context) (*PostView, error) {
	nodes, err := pvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postview.Label}
	default:
		return nil, &NotSingularError{postview.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pvq *PostViewQuery) OnlyX(ctx context.Context) *PostView {
	node, err := pvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostView ID in the query.
// Returns a *NotSingularError when more than one PostView ID is found.
// Returns a *NotFoundError when no entities are found.
func (pvq *PostViewQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postview.Label}
	default:
		err = &NotSingularError{postview.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pvq *PostViewQuery) OnlyIDX(ctx context.Context) int {
	id, err := pvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostViews.
func (pvq *PostViewQuery) All(ctx context.Context) ([]*PostView, error) {
	if err := pvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pvq *PostViewQuery) AllX(ctx context.Context) []*PostView {
	nodes, err := pvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostView IDs.
func (pvq *PostViewQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pvq.Select(postview.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pvq *PostViewQuery) IDsX(ctx context.Context) []int {
	ids, err := pvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pvq *PostViewQuery) Count(ctx context.Context) (int, error) {
	if err := pvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pvq *PostViewQuery) CountX(ctx context.Context) int {
	count, err := pvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pvq *PostViewQuery) Exist(ctx context.Context) (bool, error) {
	if err := pvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pvq *PostViewQuery) ExistX(ctx context.Context) bool {
	exist, err := pvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostViewQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pvq *PostViewQuery) Clone() *PostViewQuery {
	if pvq == nil {
		return nil
	}
	return &PostViewQuery{
		config:     pvq.config,
		limit:      pvq.limit,
		offset:     pvq.offset,
		order:      append([]OrderFunc{}, pvq.order...),
		predicates: append([]predicate.PostView{}, pvq.predicates...),
		withPost:   pvq.withPost.Clone(),
		// clone intermediate query.
		sql:    pvq.sql.Clone(),
		path:   pvq.path,
		unique: pvq.unique,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (pvq *PostViewQuery) WithPost(opts ...func(*PostQuery)) *PostViewQuery {
	query := &PostQuery{config: pvq.config}
	for _, opt := range opts {
		opt(query)
	}
	pvq.withPost = query
	return pvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostView.Query().
//		GroupBy(postview.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pvq *PostViewQuery) GroupBy(field string, fields ...string) *PostViewGroupBy {
	grbuild := &PostViewGroupBy{config: pvq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pvq.sqlQuery(ctx), nil
	}
	grbuild.label = postview.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//	}
//
//	client.PostView.Query().
//		Select(postview.FieldPostID).
//		Scan(ctx, &v)
func (pvq *PostViewQuery) Select(fields ...string) *PostViewSelect {
	pvq.fields = append(pvq.fields, fields...)
	selbuild := &PostViewSelect{PostViewQuery: pvq}
	selbuild.label = postview.Label
	selbuild.flds, selbuild.scan = &pvq.fields, selbuild.Scan
	return selbuild
}

func (pvq *PostViewQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pvq.fields {
		if !postview.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pvq.path != nil {
		prev, err := pvq.path(ctx)
		if err != nil {
			return err
		}
		pvq.sql = prev
	}
	return nil
}

func (pvq *PostViewQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostView, error) {
	var (
		nodes       = []*PostView{}
		_spec       = pvq.querySpec()
		loadedTypes = [1]bool{
			pvq.withPost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostView).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostView{config: pvq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pvq.withPost; query != nil {
		if err := pvq.loadPost(ctx, query, nodes, nil,
			func(n *PostView, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pvq *PostViewQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*PostView, init func(*PostView), assign func(*PostView, *Post)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PostView)
	for i := range nodes {
		fk := nodes[i].PostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pvq *PostViewQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pvq.querySpec()
	_spec.Node.Columns = pvq.fields
	if len(pvq.fields) > 0 {
		_spec.Unique = pvq.unique != nil && *pvq.unique
	}
	return sqlgraph.CountNodes(ctx, pvq.driver, _spec)
}

func (pvq *PostViewQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := pvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (pvq *PostViewQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postview.Table,
			Columns: postview.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postview.FieldID,
			},
		},
		From:   pvq.sql,
		Unique: true,
	}
	if unique := pvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postview.FieldID)
		for i := range fields {
			if fields[i] != postview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pvq *PostViewQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pvq.driver.Dialect())
	t1 := builder.Table(postview.Table)
	columns := pvq.fields
	if len(columns) == 0 {
		columns = postview.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pvq.sql != nil {
		selector = pvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pvq.unique != nil && *pvq.unique {
		selector.Distinct()
	}
	for _, p := range pvq.predicates {
		p(selector)
	}
	for _, p := range pvq.order {
		p(selector)
	}
	if offset := pvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostViewGroupBy is the group-by builder for PostView entities.
type PostViewGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pvgb *PostViewGroupBy) Aggregate(fns ...AggregateFunc) *PostViewGroupBy {
	pvgb.fns = append(pvgb.fns, fns...)
	return pvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pvgb *PostViewGroupBy) Scan(ctx context.Context, v any) error {
	query, err := pvgb.path(ctx)
	if err != nil {
		return err
	}
	pvgb.sql = query
	return pvgb.sqlScan(ctx, v)
}

func (pvgb *PostViewGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range pvgb.fields {
		if !postview.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pvgb *PostViewGroupBy) sqlQuery() *sql.Selector {
	selector := pvgb.sql.Select()
	aggregation := make([]string, 0, len(pvgb.fns))
	for _, fn := range pvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pvgb.fields)+len(pvgb.fns))
		for _, f := range pvgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pvgb.fields...)...)
}

// PostViewSelect is the builder for selecting fields of PostView entities.
type PostViewSelect struct {
	*PostViewQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pvs *PostViewSelect) Scan(ctx context.Context, v any) error {
	if err := pvs.prepareQuery(ctx); err != nil {
		return err
	}
	pvs.sql = pvs.PostViewQuery.sqlQuery(ctx)
	return pvs.sqlScan(ctx, v)
}

func (pvs *PostViewSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := pvs.sql.Query()
	if err := pvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
