// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kafka_laba/data-service/data/ent/post"
	"kafka_laba/data-service/data/ent/postview"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// PostView is the model entity for the PostView schema.
type PostView struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID int `json:"post_id,omitempty"`
	// User holds the value of the "user" field.
	User string `json:"user,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostViewQuery when eager-loading is set.
	Edges PostViewEdges `json:"edges"`
}

// PostViewEdges holds the relations/edges for other nodes in the graph.
type PostViewEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostViewEdges) PostOrErr() (*Post, error) {
	if e.loadedTypes[0] {
		if e.Post == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: post.Label}
		}
		return e.Post, nil
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostView) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postview.FieldID, postview.FieldPostID:
			values[i] = new(sql.NullInt64)
		case postview.FieldUser:
			values[i] = new(sql.NullString)
		case postview.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PostView", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostView fields.
func (pv *PostView) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postview.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pv.ID = int(value.Int64)
		case postview.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				pv.PostID = int(value.Int64)
			}
		case postview.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				pv.User = value.String
			}
		case postview.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pv.CreatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryPost queries the "post" edge of the PostView entity.
func (pv *PostView) QueryPost() *PostQuery {
	return (&PostViewClient{config: pv.config}).QueryPost(pv)
}

// Update returns a builder for updating this PostView.
// Note that you need to call PostView.Unwrap() before calling this method if this PostView
// was returned from a transaction, and the transaction was committed or rolled back.
func (pv *PostView) Update() *PostViewUpdateOne {
	return (&PostViewClient{config: pv.config}).UpdateOne(pv)
}

// Unwrap unwraps the PostView entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pv *PostView) Unwrap() *PostView {
	_tx, ok := pv.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostView is not a transactional entity")
	}
	pv.config.driver = _tx.drv
	return pv
}

// String implements the fmt.Stringer.
func (pv *PostView) String() string {
	var builder strings.Builder
	builder.WriteString("PostView(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pv.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", pv.PostID))
	builder.WriteString(", ")
	builder.WriteString("user=")
	builder.WriteString(pv.User)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pv.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostViews is a parsable slice of PostView.
type PostViews []*PostView

func (pv PostViews) config(cfg config) {
	for _i := range pv {
		pv[_i].config = cfg
	}
}
