// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kafka_laba/data-service/data/ent/comment"
	"kafka_laba/data-service/data/ent/post"
	"kafka_laba/data-service/data/ent/postlike"
	"kafka_laba/data-service/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescBody is the schema descriptor for body field.
	commentDescBody := commentFields[1].Descriptor()
	// comment.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	comment.BodyValidator = commentDescBody.Validators[0].(func(string) error)
	// commentDescAuthor is the schema descriptor for author field.
	commentDescAuthor := commentFields[2].Descriptor()
	// comment.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	comment.AuthorValidator = commentDescAuthor.Validators[0].(func(string) error)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[0].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescBody is the schema descriptor for body field.
	postDescBody := postFields[1].Descriptor()
	// post.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	post.BodyValidator = postDescBody.Validators[0].(func(string) error)
	// postDescAuthor is the schema descriptor for author field.
	postDescAuthor := postFields[2].Descriptor()
	// post.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	post.AuthorValidator = postDescAuthor.Validators[0].(func(string) error)
	postlikeFields := schema.PostLike{}.Fields()
	_ = postlikeFields
	// postlikeDescUser is the schema descriptor for user field.
	postlikeDescUser := postlikeFields[1].Descriptor()
	// postlike.UserValidator is a validator for the "user" field. It is called by the builders before save.
	postlike.UserValidator = postlikeDescUser.Validators[0].(func(string) error)
}
