// Code generated by ent, DO NOT EDIT.

package postlike

const (
	// Label holds the string label denoting the postlike type in the database.
	Label = "post_like"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// Table holds the table name of the postlike in the database.
	Table = "post_likes"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "post_likes"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_id"
)

// Columns holds all SQL columns for postlike fields.
var Columns = []string{
	FieldID,
	FieldPostID,
	FieldUser,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserValidator is a validator for the "user" field. It is called by the builders before save.
	UserValidator func(string) error
)
