// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kafka_laba/consumer/internal/data/ent/post"
	"kafka_laba/consumer/internal/data/ent/postview"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostViewCreate is the builder for creating a PostView entity.
type PostViewCreate struct {
	config
	mutation *PostViewMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (pvc *PostViewCreate) SetPostID(i int) *PostViewCreate {
	pvc.mutation.SetPostID(i)
	return pvc
}

// SetUser sets the "user" field.
func (pvc *PostViewCreate) SetUser(s string) *PostViewCreate {
	pvc.mutation.SetUser(s)
	return pvc
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (pvc *PostViewCreate) SetNillableUser(s *string) *PostViewCreate {
	if s != nil {
		pvc.SetUser(*s)
	}
	return pvc
}

// SetCreatedAt sets the "created_at" field.
func (pvc *PostViewCreate) SetCreatedAt(t time.Time) *PostViewCreate {
	pvc.mutation.SetCreatedAt(t)
	return pvc
}

// SetPost sets the "post" edge to the Post entity.
func (pvc *PostViewCreate) SetPost(p *Post) *PostViewCreate {
	return pvc.SetPostID(p.ID)
}

// Mutation returns the PostViewMutation object of the builder.
func (pvc *PostViewCreate) Mutation() *PostViewMutation {
	return pvc.mutation
}

// Save creates the PostView in the database.
func (pvc *PostViewCreate) Save(ctx context.Context) (*PostView, error) {
	var (
		err  error
		node *PostView
	)
	if len(pvc.hooks) == 0 {
		if err = pvc.check(); err != nil {
			return nil, err
		}
		node, err = pvc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostViewMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pvc.check(); err != nil {
				return nil, err
			}
			pvc.mutation = mutation
			if node, err = pvc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pvc.hooks) - 1; i >= 0; i-- {
			if pvc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pvc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pvc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PostView)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PostViewMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pvc *PostViewCreate) SaveX(ctx context.Context) *PostView {
	v, err := pvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvc *PostViewCreate) Exec(ctx context.Context) error {
	_, err := pvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvc *PostViewCreate) ExecX(ctx context.Context) {
	if err := pvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pvc *PostViewCreate) check() error {
	if _, ok := pvc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostView.post_id"`)}
	}
	if _, ok := pvc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PostView.created_at"`)}
	}
	if _, ok := pvc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostView.post"`)}
	}
	return nil
}

func (pvc *PostViewCreate) sqlSave(ctx context.Context) (*PostView, error) {
	_node, _spec := pvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pvc *PostViewCreate) createSpec() (*PostView, *sqlgraph.CreateSpec) {
	var (
		_node = &PostView{config: pvc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: postview.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postview.FieldID,
			},
		}
	)
	if value, ok := pvc.mutation.User(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postview.FieldUser,
		})
		_node.User = value
	}
	if value, ok := pvc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postview.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := pvc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postview.PostTable,
			Columns: []string{postview.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostViewCreateBulk is the builder for creating many PostView entities in bulk.
type PostViewCreateBulk struct {
	config
	builders []*PostViewCreate
}

// Save creates the PostView entities in the database.
func (pvcb *PostViewCreateBulk) Save(ctx context.Context) ([]*PostView, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pvcb.builders))
	nodes := make([]*PostView, len(pvcb.builders))
	mutators := make([]Mutator, len(pvcb.builders))
	for i := range pvcb.builders {
		func(i int, root context.Context) {
			builder := pvcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pvcb *PostViewCreateBulk) SaveX(ctx context.Context) []*PostView {
	v, err := pvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pvcb *PostViewCreateBulk) Exec(ctx context.Context) error {
	_, err := pvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvcb *PostViewCreateBulk) ExecX(ctx context.Context) {
	if err := pvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
