// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kafka_laba/consumer/internal/data/ent/post"
	"kafka_laba/consumer/internal/data/ent/postlike"
	"kafka_laba/consumer/internal/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostLikeQuery is the builder for querying PostLike entities.
type PostLikeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PostLike
	withPost   *PostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostLikeQuery builder.
func (plq *PostLikeQuery) Where(ps ...predicate.PostLike) *PostLikeQuery {
	plq.predicates = append(plq.predicates, ps...)
	return plq
}

// Limit adds a limit step to the query.
func (plq *PostLikeQuery) Limit(limit int) *PostLikeQuery {
	plq.limit = &limit
	return plq
}

// Offset adds an offset step to the query.
func (plq *PostLikeQuery) Offset(offset int) *PostLikeQuery {
	plq.offset = &offset
	return plq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (plq *PostLikeQuery) Unique(unique bool) *PostLikeQuery {
	plq.unique = &unique
	return plq
}

// Order adds an order step to the query.
func (plq *PostLikeQuery) Order(o ...OrderFunc) *PostLikeQuery {
	plq.order = append(plq.order, o...)
	return plq
}

// QueryPost chains the current query on the "post" edge.
func (plq *PostLikeQuery) QueryPost() *PostQuery {
	query := &PostQuery{config: plq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := plq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := plq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postlike.Table, postlike.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, postlike.PostTable, postlike.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(plq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostLike entity from the query.
// Returns a *NotFoundError when no PostLike was found.
func (plq *PostLikeQuery) First(ctx context.Context) (*PostLike, error) {
	nodes, err := plq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postlike.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (plq *PostLikeQuery) FirstX(ctx context.Context) *PostLike {
	node, err := plq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostLike ID from the query.
// Returns a *NotFoundError when no PostLike ID was found.
func (plq *PostLikeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postlike.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (plq *PostLikeQuery) FirstIDX(ctx context.Context) int {
	id, err := plq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostLike entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostLike entity is found.
// Returns a *NotFoundError when no PostLike entities are found.
func (plq *PostLikeQuery) Only(ctx context.Context) (*PostLike, error) {
	nodes, err := plq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postlike.Label}
	default:
		return nil, &NotSingularError{postlike.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (plq *PostLikeQuery) OnlyX(ctx context.Context) *PostLike {
	node, err := plq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostLike ID in the query.
// Returns a *NotSingularError when more than one PostLike ID is found.
// Returns a *NotFoundError when no entities are found.
func (plq *PostLikeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postlike.Label}
	default:
		err = &NotSingularError{postlike.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (plq *PostLikeQuery) OnlyIDX(ctx context.Context) int {
	id, err := plq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostLikes.
func (plq *PostLikeQuery) All(ctx context.Context) ([]*PostLike, error) {
	if err := plq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return plq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (plq *PostLikeQuery) AllX(ctx context.Context) []*PostLike {
	nodes, err := plq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostLike IDs.
func (plq *PostLikeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := plq.Select(postlike.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (plq *PostLikeQuery) IDsX(ctx context.Context) []int {
	ids, err := plq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (plq *PostLikeQuery) Count(ctx context.Context) (int, error) {
	if err := plq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return plq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (plq *PostLikeQuery) CountX(ctx context.Context) int {
	count, err := plq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (plq *PostLikeQuery) Exist(ctx context.Context) (bool, error) {
	if err := plq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return plq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (plq *PostLikeQuery) ExistX(ctx context.Context) bool {
	exist, err := plq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostLikeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (plq *PostLikeQuery) Clone() *PostLikeQuery {
	if plq == nil {
		return nil
	}
	return &PostLikeQuery{
		config:     plq.config,
		limit:      plq.limit,
		offset:     plq.offset,
		order:      append([]OrderFunc{}, plq.order...),
		predicates: append([]predicate.PostLike{}, plq.predicates...),
		withPost:   plq.withPost.Clone(),
		// clone intermediate query.
		sql:    plq.sql.Clone(),
		path:   plq.path,
		unique: plq.unique,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (plq *PostLikeQuery) WithPost(opts ...func(*PostQuery)) *PostLikeQuery {
	query := &PostQuery{config: plq.config}
	for _, opt := range opts {
		opt(query)
	}
	plq.withPost = query
	return plq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostLike.Query().
//		GroupBy(postlike.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (plq *PostLikeQuery) GroupBy(field string, fields ...string) *PostLikeGroupBy {
	grbuild := &PostLikeGroupBy{config: plq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := plq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return plq.sqlQuery(ctx), nil
	}
	grbuild.label = postlike.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//	}
//
//	client.PostLike.Query().
//		Select(postlike.FieldPostID).
//		Scan(ctx, &v)
func (plq *PostLikeQuery) Select(fields ...string) *PostLikeSelect {
	plq.fields = append(plq.fields, fields...)
	selbuild := &PostLikeSelect{PostLikeQuery: plq}
	selbuild.label = postlike.Label
	selbuild.flds, selbuild.scan = &plq.fields, selbuild.Scan
	return selbuild
}

func (plq *PostLikeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range plq.fields {
		if !postlike.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if plq.path != nil {
		prev, err := plq.path(ctx)
		if err != nil {
			return err
		}
		plq.sql = prev
	}
	return nil
}

func (plq *PostLikeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostLike, error) {
	var (
		nodes       = []*PostLike{}
		_spec       = plq.querySpec()
		loadedTypes = [1]bool{
			plq.withPost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostLike).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostLike{config: plq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, plq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := plq.withPost; query != nil {
		if err := plq.loadPost(ctx, query, nodes, nil,
			func(n *PostLike, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (plq *PostLikeQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*PostLike, init func(*PostLike), assign func(*PostLike, *Post)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PostLike)
	for i := range nodes {
		fk := nodes[i].PostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (plq *PostLikeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := plq.querySpec()
	_spec.Node.Columns = plq.fields
	if len(plq.fields) > 0 {
		_spec.Unique = plq.unique != nil && *plq.unique
	}
	return sqlgraph.CountNodes(ctx, plq.driver, _spec)
}

func (plq *PostLikeQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := plq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (plq *PostLikeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postlike.Table,
			Columns: postlike.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postlike.FieldID,
			},
		},
		From:   plq.sql,
		Unique: true,
	}
	if unique := plq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := plq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postlike.FieldID)
		for i := range fields {
			if fields[i] != postlike.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := plq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := plq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := plq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := plq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (plq *PostLikeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(plq.driver.Dialect())
	t1 := builder.Table(postlike.Table)
	columns := plq.fields
	if len(columns) == 0 {
		columns = postlike.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if plq.sql != nil {
		selector = plq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if plq.unique != nil && *plq.unique {
		selector.Distinct()
	}
	for _, p := range plq.predicates {
		p(selector)
	}
	for _, p := range plq.order {
		p(selector)
	}
	if offset := plq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := plq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostLikeGroupBy is the group-by builder for PostLike entities.
type PostLikeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (plgb *PostLikeGroupBy) Aggregate(fns ...AggregateFunc) *PostLikeGroupBy {
	plgb.fns = append(plgb.fns, fns...)
	return plgb
}

// Scan applies the group-by query and scans the result into the given value.
func (plgb *PostLikeGroupBy) Scan(ctx context.Context, v any) error {
	query, err := plgb.path(ctx)
	if err != nil {
		return err
	}
	plgb.sql = query
	return plgb.sqlScan(ctx, v)
}

func (plgb *PostLikeGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range plgb.fields {
		if !postlike.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := plgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := plgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (plgb *PostLikeGroupBy) sqlQuery() *sql.Selector {
	selector := plgb.sql.Select()
	aggregation := make([]string, 0, len(plgb.fns))
	for _, fn := range plgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(plgb.fields)+len(plgb.fns))
		for _, f := range plgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(plgb.fields...)...)
}

// PostLikeSelect is the builder for selecting fields of PostLike entities.
type PostLikeSelect struct {
	*PostLikeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pls *PostLikeSelect) Scan(ctx context.Context, v any) error {
	if err := pls.prepareQuery(ctx); err != nil {
		return err
	}
	pls.sql = pls.PostLikeQuery.sqlQuery(ctx)
	return pls.sqlScan(ctx, v)
}

func (pls *PostLikeSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := pls.sql.Query()
	if err := pls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
