// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kafka_laba/consumer/internal/data/ent/post"
	"kafka_laba/consumer/internal/data/ent/postview"
	"kafka_laba/consumer/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostViewUpdate is the builder for updating PostView entities.
type PostViewUpdate struct {
	config
	hooks    []Hook
	mutation *PostViewMutation
}

// Where appends a list predicates to the PostViewUpdate builder.
func (pvu *PostViewUpdate) Where(ps ...predicate.PostView) *PostViewUpdate {
	pvu.mutation.Where(ps...)
	return pvu
}

// SetPostID sets the "post_id" field.
func (pvu *PostViewUpdate) SetPostID(i int) *PostViewUpdate {
	pvu.mutation.SetPostID(i)
	return pvu
}

// SetUser sets the "user" field.
func (pvu *PostViewUpdate) SetUser(s string) *PostViewUpdate {
	pvu.mutation.SetUser(s)
	return pvu
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (pvu *PostViewUpdate) SetNillableUser(s *string) *PostViewUpdate {
	if s != nil {
		pvu.SetUser(*s)
	}
	return pvu
}

// ClearUser clears the value of the "user" field.
func (pvu *PostViewUpdate) ClearUser() *PostViewUpdate {
	pvu.mutation.ClearUser()
	return pvu
}

// SetCreatedAt sets the "created_at" field.
func (pvu *PostViewUpdate) SetCreatedAt(t time.Time) *PostViewUpdate {
	pvu.mutation.SetCreatedAt(t)
	return pvu
}

// SetPost sets the "post" edge to the Post entity.
func (pvu *PostViewUpdate) SetPost(p *Post) *PostViewUpdate {
	return pvu.SetPostID(p.ID)
}

// Mutation returns the PostViewMutation object of the builder.
func (pvu *PostViewUpdate) Mutation() *PostViewMutation {
	return pvu.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (pvu *PostViewUpdate) ClearPost() *PostViewUpdate {
	pvu.mutation.ClearPost()
	return pvu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pvu *PostViewUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pvu.hooks) == 0 {
		if err = pvu.check(); err != nil {
			return 0, err
		}
		affected, err = pvu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostViewMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pvu.check(); err != nil {
				return 0, err
			}
			pvu.mutation = mutation
			affected, err = pvu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pvu.hooks) - 1; i >= 0; i-- {
			if pvu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pvu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pvu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pvu *PostViewUpdate) SaveX(ctx context.Context) int {
	affected, err := pvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pvu *PostViewUpdate) Exec(ctx context.Context) error {
	_, err := pvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvu *PostViewUpdate) ExecX(ctx context.Context) {
	if err := pvu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pvu *PostViewUpdate) check() error {
	if _, ok := pvu.mutation.PostID(); pvu.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostView.post"`)
	}
	return nil
}

func (pvu *PostViewUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postview.Table,
			Columns: postview.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postview.FieldID,
			},
		},
	}
	if ps := pvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pvu.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postview.FieldUser,
		})
	}
	if pvu.mutation.UserCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: postview.FieldUser,
		})
	}
	if value, ok := pvu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postview.FieldCreatedAt,
		})
	}
	if pvu.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postview.PostTable,
			Columns: []string{postview.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pvu.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postview.PostTable,
			Columns: []string{postview.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PostViewUpdateOne is the builder for updating a single PostView entity.
type PostViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostViewMutation
}

// SetPostID sets the "post_id" field.
func (pvuo *PostViewUpdateOne) SetPostID(i int) *PostViewUpdateOne {
	pvuo.mutation.SetPostID(i)
	return pvuo
}

// SetUser sets the "user" field.
func (pvuo *PostViewUpdateOne) SetUser(s string) *PostViewUpdateOne {
	pvuo.mutation.SetUser(s)
	return pvuo
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (pvuo *PostViewUpdateOne) SetNillableUser(s *string) *PostViewUpdateOne {
	if s != nil {
		pvuo.SetUser(*s)
	}
	return pvuo
}

// ClearUser clears the value of the "user" field.
func (pvuo *PostViewUpdateOne) ClearUser() *PostViewUpdateOne {
	pvuo.mutation.ClearUser()
	return pvuo
}

// SetCreatedAt sets the "created_at" field.
func (pvuo *PostViewUpdateOne) SetCreatedAt(t time.Time) *PostViewUpdateOne {
	pvuo.mutation.SetCreatedAt(t)
	return pvuo
}

// SetPost sets the "post" edge to the Post entity.
func (pvuo *PostViewUpdateOne) SetPost(p *Post) *PostViewUpdateOne {
	return pvuo.SetPostID(p.ID)
}

// Mutation returns the PostViewMutation object of the builder.
func (pvuo *PostViewUpdateOne) Mutation() *PostViewMutation {
	return pvuo.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (pvuo *PostViewUpdateOne) ClearPost() *PostViewUpdateOne {
	pvuo.mutation.ClearPost()
	return pvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pvuo *PostViewUpdateOne) Select(field string, fields ...string) *PostViewUpdateOne {
	pvuo.fields = append([]string{field}, fields...)
	return pvuo
}

// Save executes the query and returns the updated PostView entity.
func (pvuo *PostViewUpdateOne) Save(ctx context.Context) (*PostView, error) {
	var (
		err  error
		node *PostView
	)
	if len(pvuo.hooks) == 0 {
		if err = pvuo.check(); err != nil {
			return nil, err
		}
		node, err = pvuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostViewMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pvuo.check(); err != nil {
				return nil, err
			}
			pvuo.mutation = mutation
			node, err = pvuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pvuo.hooks) - 1; i >= 0; i-- {
			if pvuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pvuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pvuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PostView)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PostViewMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pvuo *PostViewUpdateOne) SaveX(ctx context.Context) *PostView {
	node, err := pvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pvuo *PostViewUpdateOne) Exec(ctx context.Context) error {
	_, err := pvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pvuo *PostViewUpdateOne) ExecX(ctx context.Context) {
	if err := pvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pvuo *PostViewUpdateOne) check() error {
	if _, ok := pvuo.mutation.PostID(); pvuo.mutation.PostCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PostView.post"`)
	}
	return nil
}

func (pvuo *PostViewUpdateOne) sqlSave(ctx context.Context) (_node *PostView, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   postview.Table,
			Columns: postview.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postview.FieldID,
			},
		},
	}
	id, ok := pvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postview.FieldID)
		for _, f := range fields {
			if !postview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pvuo.mutation.User(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postview.FieldUser,
		})
	}
	if pvuo.mutation.UserCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: postview.FieldUser,
		})
	}
	if value, ok := pvuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postview.FieldCreatedAt,
		})
	}
	if pvuo.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postview.PostTable,
			Columns: []string{postview.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pvuo.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postview.PostTable,
			Columns: []string{postview.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostView{config: pvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
