// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kafka_laba/consumer/internal/data/ent/post"
	"kafka_laba/consumer/internal/data/ent/postlike"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostLikeCreate is the builder for creating a PostLike entity.
type PostLikeCreate struct {
	config
	mutation *PostLikeMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (plc *PostLikeCreate) SetPostID(i int) *PostLikeCreate {
	plc.mutation.SetPostID(i)
	return plc
}

// SetUser sets the "user" field.
func (plc *PostLikeCreate) SetUser(s string) *PostLikeCreate {
	plc.mutation.SetUser(s)
	return plc
}

// SetCreatedAt sets the "created_at" field.
func (plc *PostLikeCreate) SetCreatedAt(t time.Time) *PostLikeCreate {
	plc.mutation.SetCreatedAt(t)
	return plc
}

// SetPost sets the "post" edge to the Post entity.
func (plc *PostLikeCreate) SetPost(p *Post) *PostLikeCreate {
	return plc.SetPostID(p.ID)
}

// Mutation returns the PostLikeMutation object of the builder.
func (plc *PostLikeCreate) Mutation() *PostLikeMutation {
	return plc.mutation
}

// Save creates the PostLike in the database.
func (plc *PostLikeCreate) Save(ctx context.Context) (*PostLike, error) {
	var (
		err  error
		node *PostLike
	)
	if len(plc.hooks) == 0 {
		if err = plc.check(); err != nil {
			return nil, err
		}
		node, err = plc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostLikeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = plc.check(); err != nil {
				return nil, err
			}
			plc.mutation = mutation
			if node, err = plc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(plc.hooks) - 1; i >= 0; i-- {
			if plc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = plc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, plc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PostLike)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PostLikeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (plc *PostLikeCreate) SaveX(ctx context.Context) *PostLike {
	v, err := plc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plc *PostLikeCreate) Exec(ctx context.Context) error {
	_, err := plc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plc *PostLikeCreate) ExecX(ctx context.Context) {
	if err := plc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (plc *PostLikeCreate) check() error {
	if _, ok := plc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostLike.post_id"`)}
	}
	if _, ok := plc.mutation.User(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required field "PostLike.user"`)}
	}
	if v, ok := plc.mutation.User(); ok {
		if err := postlike.UserValidator(v); err != nil {
			return &ValidationError{Name: "user", err: fmt.Errorf(`ent: validator failed for field "PostLike.user": %w`, err)}
		}
	}
	if _, ok := plc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PostLike.created_at"`)}
	}
	if _, ok := plc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostLike.post"`)}
	}
	return nil
}

func (plc *PostLikeCreate) sqlSave(ctx context.Context) (*PostLike, error) {
	_node, _spec := plc.createSpec()
	if err := sqlgraph.CreateNode(ctx, plc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (plc *PostLikeCreate) createSpec() (*PostLike, *sqlgraph.CreateSpec) {
	var (
		_node = &PostLike{config: plc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: postlike.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postlike.FieldID,
			},
		}
	)
	if value, ok := plc.mutation.User(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: postlike.FieldUser,
		})
		_node.User = value
	}
	if value, ok := plc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: postlike.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := plc.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postlike.PostTable,
			Columns: []string{postlike.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: post.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostLikeCreateBulk is the builder for creating many PostLike entities in bulk.
type PostLikeCreateBulk struct {
	config
	builders []*PostLikeCreate
}

// Save creates the PostLike entities in the database.
func (plcb *PostLikeCreateBulk) Save(ctx context.Context) ([]*PostLike, error) {
	specs := make([]*sqlgraph.CreateSpec, len(plcb.builders))
	nodes := make([]*PostLike, len(plcb.builders))
	mutators := make([]Mutator, len(plcb.builders))
	for i := range plcb.builders {
		func(i int, root context.Context) {
			builder := plcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostLikeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, plcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, plcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, plcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (plcb *PostLikeCreateBulk) SaveX(ctx context.Context) []*PostLike {
	v, err := plcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plcb *PostLikeCreateBulk) Exec(ctx context.Context) error {
	_, err := plcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plcb *PostLikeCreateBulk) ExecX(ctx context.Context) {
	if err := plcb.Exec(ctx); err != nil {
		panic(err)
	}
}
