// Code generated by ent, DO NOT EDIT.

package post

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeLikes holds the string denoting the likes edge name in mutations.
	EdgeLikes = "likes"
	// EdgeViews holds the string denoting the views edge name in mutations.
	EdgeViews = "views"
	// Table holds the table name of the post in the database.
	Table = "posts"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "post_id"
	// LikesTable is the table that holds the likes relation/edge.
	LikesTable = "post_likes"
	// LikesInverseTable is the table name for the PostLike entity.
	// It exists in this package in order to avoid circular dependency with the "postlike" package.
	LikesInverseTable = "post_likes"
	// LikesColumn is the table column denoting the likes relation/edge.
	LikesColumn = "post_id"
	// ViewsTable is the table that holds the views relation/edge.
	ViewsTable = "post_views"
	// ViewsInverseTable is the table name for the PostView entity.
	// It exists in this package in order to avoid circular dependency with the "postview" package.
	ViewsInverseTable = "post_views"
	// ViewsColumn is the table column denoting the views relation/edge.
	ViewsColumn = "post_id"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldBody,
	FieldAuthor,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	AuthorValidator func(string) error
)
